site_name:  LunaX - Betaflight Docs
use_directory_urls: true

nav:
  - 'Home' : index.md
  - Release-Notes : 
     - 'BF 4.2 Release' : 'bf_release_4.2.md'
     - 'BF 4.1 Release' : 'bf_release_4.1.md'
     - 'BF 4.0 Release' : 'bf_release_4.0.md'
  - 'Betaflight' : 
     - 'Filter': 'bf_filter.md'
     - 'Blackbox-Analyse' : 'bf_bb_analyse.md'
     - 'PID-Controller' : 'bf_pid_controller.md'
     - 'Tuning' : 'bf_tuning.md'
     - 'Tunig-Parameter' : 'bf_tuning_parameters.md'
     - 'DMin' : 'bf_dmin.md'
  - 'About': about.md
  
#theme: 'windmill'
theme:
   name: windmill
   custom_dir: 'mkdocs-windmill/'
   static_templates: [404.html]
   search_index_only: true
   include_search_page: true  

plugins:
  - search:
      lang: ['de','en']
  
  - markdownmermaid
  - pdf-export:
      verbose: false
      combined : true
      combined_output_path: pdf/bf_doc_all.pdf
      enabled_if_env : ENABLE_PDF_EXPORT
        
markdown_extensions:
  - toc:
        baselevel: 2
        permalink: '#'
  - footnotes
         
extra:
   logo: images/LunaX_Font.png
   article_nav_top: false
   article_nav_bottom: false
   
 
extra_javascript:
   - js/mermaid.min.js
   

extra_css:
   - css/pdf.css
   
