site_name:  LunaX - Betaflight Docs
use_directory_urls: true

#theme:
#   name: material
#   logo: images/lunax_logo.png
#   favicon: images/lunax_logo.png
#   features:
#      - search.highlight   
      
theme:
   name: windmill

#theme: 
#   name: 'rtd-dropdown'

#theme:
#   name: null
#   custom_dir: 'cinder/cinder'
#   colorscheme: github
#   highlightjs: true
#   hljs_languages:
#      - yaml
#   static_templates: [404.html]
#   search_index_only: true
#   include_search_page: true  


nav:
  - 'Home' : index.md
  - BF-Release-Notes : 
     - 'BF 4.2 Release' : 'bf_release_4.2.md'
     - 'BF 4.1 Release' : 'bf_release_4.1.md'
     - 'BF 4.0 Release' : 'bf_release_4.0.md'
  - 'Betaflight' : 
     - 'Filter': 'bf_filter.md'
     - 'Blackbox-Analyse' : 'bf_bb_analyse.md'
     - 'PID-Controller' : 'bf_pid_controller.md'
     - 'Tuning' : 'bf_tuning.md'
     - 'Tuning-Parameter' : 'bf_tuning_parameters.md'
     - 'Tuning-Logbuch' : 'bf_tuning_logbuch.md'
     - 'DMin' : 'bf_dmin.md'
     - 'CLI': 'bf_cli.md'
  - 'About': about.md
  
plugins:
  - search:
      lang: ['de','en']
      separator: '[\s\-\.]+'
      
#  - mermaid2
  - markdownmermaid
  - pdf-export:
      verbose: false
      combined : true
      media_type: print
      combined_output_path: pdf/bf_doc_all.pdf
      enabled_if_env : ENABLE_PDF_EXPORT
        
markdown_extensions:
  - toc:
        baselevel: 2
        permalink: '#'
  - footnotes
  - admonition
  - attr_list

#  - pymdownx.superfences:
#      # make exceptions to highlighting of code:
#      custom_fences:
#        - name: mermaid
#          class: mermaid
#          format: !!python/name:mermaid2.fence_mermaid         

extra:
   logo: images/LunaX_Font.png
   article_nav_top: false
   article_nav_bottom: false
   
 
extra_javascript:
   - js/mermaid.min.js
#   - https://unpkg.com/mermaid/dist/mermaid.min.js   

extra_css:
   - css/pdf.css
   
